### ISSUE TITLE
Consider lowering node version specified in package.json

### ISSUE THREAD

**Issue by santialbo** [tylerjpeterson/accent-fold#1]
If there's no other reasons that require the current version set on package.json. I've run the tests with node version as low as 5.0.0 and they all pass.

Thanks a lot for writing this package.

**Comment by tylerjpeterson** [comment]
@santialbo - I was able to reduce down to version `4.8.7` without creating issues with the testing suite. Also cleaned out some unnecessary dev dependencies. 

Published to npm as `v1.0.1`, and thanks for brining it to my attention!

**Comment by santialbo-actimo** [comment]
Thanks a lot for the super fast reply 👍
